### ISSUE TITLE
failed to make a request

### ISSUE THREAD

**Issue by paul19942** [Squidex/squidex#128]
i tried to create a new schema but always i get failed to make the request
can i know what is the problem?

**Comment by SebastianStehle** [comment]
Where? In the Cloud version or your local instance?

**Comment by paul19942** [comment]
cloud version

**Comment by SebastianStehle** [comment]
Thank you, I will have a look.

**Comment by SebastianStehle** [comment]
Hi, 

can you try it again? I think the reason was our event consumers. We use a CQRS architecture: https://docs.squidex.io/02-architecture/01-overview.html

The events (e.g. AppCreated) are consumed in the background and we rebuild this system to make it easier to maintain and understand. But unfortunately there was a bug. I am sorry.

The good think: We can never loose any data, because events are append only.

**Comment by paul19942** [comment]
ok thnx

**Comment by paul19942** [comment]
i can't access documentation https://cloud.squidex.io/api/content/appmarwa/docs

**Comment by SebastianStehle** [comment]
Thank you, will fix it asap.

**Comment by SebastianStehle** [comment]
Lol, I found an unreproducable bug in .NET Framework :(

**Comment by paul19942** [comment]
hhhh ok

**Comment by paul19942** [comment]
i try to update a field of schema  using api but i always get 403
put https://cloud.squidex.io/api/apps/appmarwa/schemas/product/fields/1
i added the key
and the json is:
{
  "properties": {
    "label": "string",
    "hints": "string",
    "placeholder": "string",
    "isRequired": true,
    "isListField": false,
    "fieldType": "string"
  }
}
can u help me please
