### ISSUE TITLE
[Question] Did project have any plan to authorize Schema?

### ISSUE THREAD

**Issue by mjhpour** [Squidex/squidex#209]
Hello, and thank you for this good project @SebastianStehle .

I have some question. 

We have just one type of users, the `Contributor`. Imagine that someone wants to create a user in the schema and get access to some `Schema` for them. can we handle this type of content with this system? Did you have any plan in design or roadmap for it? or this type of content completely not supported by this project?

**Comment by SebastianStehle** [comment]
Sure, we aware that it is needed sooner or later. But the priorities also depend on what others want and so far this has not been requested many times.

It is possible with scripting: https://medium.com/squidex/updates-from-squidex-e3e6550d8cd1 ... but of course not the ideal situation, because the UI does not reflect your policies then.

**Comment by SebastianStehle** [comment]
https://trello.com/c/KZ371zl9/34-permissions-per-schemas
