### ISSUE TITLE
[Question] Anythings for plugin system?

### ISSUE THREAD

**Issue by mjhpour** [Squidex/squidex#210]
Did we have anything for plugin system? I see just one issue about move complex query to the plugin.

**Comment by SebastianStehle** [comment]
Indeed there is an issue for complex queries, but I postponed to merge it, because at the moment I cannot maintain it yet. 

I would say that a plugin system has 2 parts

1. Contracts (Interfaces) and UI extensions
2. System to discover, load and unload them. 

For both parts I have no good solution yet. The complex query thing was something like a draft, but not a fully functional plugin system. Our idea was to make something like apps. Extensions that are built on top of Squidex and not integrated, such an App could be something like auth0 for example.

What kind of plugins do you have in mind?

**Comment by mjhpour** [comment]
Extention on top of the Squidex is a good idea. But if we want to change for example API Layer or change the Infrastructure layer and add more functionality to application flow, we should add our codes right into the core. Develop and change the functionality without changing the base app with the plugin.

**Comment by SebastianStehle** [comment]
Totally agree. We could use the Orchard.Core Framework for that.
