### ISSUE TITLE
Quota issues

### ISSUE THREAD

**Issue by BoasE** [Squidex/squidex#256]
First the quota is too soon gone.

we have a quota 1500k and now with 1401 we get "too many requests" responses.

also when reached the quota i can't even use the squidex ui to add or remove entries

**Comment by SebastianStehle** [comment]
The first one sounds like a bug, because you should have an buffer of 10%.

The API calls are measure for all clients, the UI is also one. The reason is that some customers have their own management UI, some not. So it would be unfair to exclude the UI. Furthermore the costs are the same for you us.
