### ISSUE TITLE
Show Contributor Email Adresses

### ISSUE THREAD

**Issue by christianuhlcc** [Squidex/squidex#269]
When adding "contributors" to an app, it would be cool to see the email adresses of the users, instead of just their names.

In our case here the person "Oleg" had a private and a business account, and I coudn't see which one to add. We had to to try it out to find the right one. The more users you get the more important it might become.

![bildschirmfoto 2018-04-10 um 10 44 54](https://user-images.githubusercontent.com/5628574/38547270-ff71ce2c-3cae-11e8-97a7-c08f106bcb60.png)

**Comment by SebastianStehle** [comment]
It kind of makes sense, BUT the problem is that we just removed the email address, because it leads to privacy issues. You would be able to add another user then, see his email-address and remove him again.

We have 2 options:

1. A user setting to show the email address to others.
2. An approach where you invite the user first  and once he accepts the invitation you see his email address.

I would prefer option 2, because it is easier to communicate and restricts the visibility of your email address, but given our roadmap is full of stuff we can not implement it before May. I would just change the display name for one of the Olegs.
