### ISSUE TITLE
Workflow for versioning

### ISSUE THREAD

**Issue by jiveabillion** [Squidex/squidex#281]
Are there plans to add a workflow to content publishing? It seems as though it can only do "Draft" when creating a new content item, but it will not allow a draft version when updating after a content item has been published.

It would be great if workflows could be defined to allow the status of a content item to be updated for steps like Approval by different levels of authority.  For example:

1. Draft
2. Submitted for Approval
3. Approved by lower level person
4. Approved by Highest Level Person
5. Published

At the bare minimum, it would be great to save changes to a content item without publishing those changes immediately. The previously published version would remain published until the latest version is published. 

It would also be great if you could roll back to a previous version by making it the published version.

The read API would only serve up published versions. An Admin or "preview" API could always serve up the latest version, regardless of the status.

Do you believe that this would be difficult to implement? I would like to make an attempt to do so, but I would welcome some guidance as to where/how this modification could be implemented.

**Comment by jiveabillion** [comment]
I see now that you already have some cards in Trello for these requests. I have some experience using Kentico CMS, which does have the custom workflow definitions and the type of versioning that I mentioned. If I can be of some help in planning how to implement these features, let me know.

**Comment by jiveabillion** [comment]
In Kentico Cloud, the default, immutable workflow steps are Draft, Scheduled, and Published.  Additional Workflow steps can be added in between Draft and Scheduled and the order of these additional steps can be changed. In the UI, when you update the workflow step of a content item to "Published", it gives you the option of publishing it now or scheduling it to be published. If you choose to schedule it, you choose a date and time and it will become the published version at that time. In their regular CMS, there is a scheduled task that runs every minute that checks for documents that are scheduled to be published and publishes them if they have reached their scheduled date and time. I assume they have something similar that runs in their Kentico Cloud implementation.

One thing that they don't seem to have done in Kentico Cloud that that have done in their CMS is allow the creation of multiple workflow definitions and the ability to assign specific workflow definitions to specific content types. This was very useful in their regular CMS, so I am unsure why they did not include it in their Cloud CMS. Regardless, I think that it would be good to include that feature in Squidex as well.

I believe that once you have completed adding the ability to save drafts of content edits without publishing, then adding in additional workflow steps (which really just set a status on the content item), would be fairly simple.

**Comment by jiveabillion** [comment]
It looks like the basic workflow of saving contents needs to change in order to implement saving of draft  version of a previously published content item without publishing it before we can add additional workflow steps. 

Old way:
1. Click Create New - content item not inserted into database yet
2. Save as Draft - Action is saved to history
3. Publish - Action is saved to history
4. Make changes 
5. Save - Changes are applied to the published version. Action is saved to history
 
Proposed new way (This is basically how Kentico Cloud does it, and it works fairly well):

1. Click Create New - Content Item created in database in Draft status with no data. Generic title will be used in grid
2. Fill out form, changes can be saved automatically (this is optional)
3. Click Save - no actions are stored (only necessary if we don't save changes automatically)
4. Choose a workflow step to transition to
5. Choose a Publish workflow step - Published documents cannot be edited. Instead, a new version must be created while the published version remains.
     A. Schedule - Select a date and time to publish
     B. Publish Immediately
6. Click "Create new Version" - Will add a create a new draft version of this same document in the database
7. Repeat steps 2-6 as needed - Each time you click "Create New" or "Create New Version" a new version will be inserted in the database and should be selectable in the Activity pane. If a draft version exists, a button to restore a version should appear and it should copy the older version's data to the form so that it can be saved/edited before publishing again. The Activity Pane will no longer need to contain every single change, instead it will just list each version that has existed.

**Comment by SebastianStehle** [comment]
I totally agree, this needs to be done. I already have a working first version and I hope to release until end of April. 

The approach is that once you publish a content you can either create a proposal for an update or save the published version directly. It works with relatively few changes, but is not perfect yet. In the long term I would have something more advanced, like the approach from kentico where you create a new version explicitely and each version has its own workflow.

But in contrast to kentico I would also like to edit published versions directly, because it depends on your content if this suitable or not, e.g. for this use case: https://medium.com/squidex/use-squidex-to-manage-translations-for-your-web-application-9682a312b7d2

It might be worth to also handle content variations when we touch this feature.

Btw: You can already jump back to an older version, by loading the version and saving it again. We never do updates or deletions in Squidex, so you cannot loose information.

**Comment by jiveabillion** [comment]
I see you want to be able to edit things inline in the grid, which may require editing the published version. I am not sure that is a great idea or not, because the use case seems like it would not be required very often.  Perhaps inline editing like that could be done by having checkboxes on the grid to do a mass action, like check a few items and have a button at the top of the grid for actions, two of which would be "Create New Version" and "Publish". So editing inline would only work on drafts and the process for editing several items in the grid would be 
1. Filter the grid as much as you can to find the list of items you want to edit
2. Check the checkbox next to each item you want to edit ( you can add complex selections where you can select range in between two boxes to make this quicker)
3. Click the Mass Action button (could rename this) and click "Create New Version(s)" - New versions would be created and the grid refreshed to show they are in draft status
4. Edit the values inline until you are finished
5. Check the boxes again to select the items you wish to publish
6. Click the Mass Action button again and choose "Publish", which will publish the selected items and refresh the grid.

This method protects the published data, allows you to make updates and verify them before any live published data is updated (this is actually very important because you  probably don't want typos or incomplete work being shown to front end visitors) It also will prevent unfinished changes from being pushed via webhooks or other rules that are triggered only on Publish actions.


Regarding the "never do updates or deletions in Squidex" comment. I see where that is currently true because every time you click "Save" it adds to the archive collection, but I don't think it's necessary to save every step of editing content once you have implemented control of the versioning like Kentico Cloud has. You would only need to store the draft version and each version that has been published. It is uncommon that a user would need to restore a version that was a work in progress. Unless you feel that this feature is of utmost importance, changing it to work like I described in my previous comment would free up the issue I mentioned where adding a separate collection to store the "Latest" versions of every content item to make querying that content easier an non issue, because we would be saving storage space already by not inserting new records into the archive collection on every save, instead we would insert into the archive collection on every "Create New" or "Create New Version" and update that version in the archive collection until it's published. I think this would actually make the process of dealing with the Latest version a lot easier.

I agree that it may be worth it to handle content variations, like language versions when this feature is implemented, although it would add another level of complexity to getting the versioning implemented.

From what I have gathered, the way Kentico Cloud handles language versions is it allows you to switch between languages in the content item form. It seems as though you must first create a content item version for the default language. After creating that version, you can go into the form and choose an alternative language, and it will create a draft version of that language for you to edit. You can then, optionally, click a button that will copy over the content from the default language and then allow you to edit it. You can see in the URL that there is an empty GUID when you have the default language version selected, and it changes to a language GUID when you switch languages in the form and the GUID that seems to represent the Content Item Id remains the same. From this information, I gather that Kentico is using the Content Item Id + Language Id to identify a piece of content. I imagine that their queries take an optional LanguageId parameter and it filters the results where the languageId is Empty or equal to the passed LanguageId. I am not sure how they would query lists to return only results where it returns the specified language version of specific documents AND the documents where only the default language version exists AND ignoring the default language version of documents where a version with the specified language does exist. I am not very familiar with NoSQL queries yet though. I do know that it would be a complex query in RDB SQL. Either way, Kentico has been doing multilingual CMS work for several years, so I trust that their way of handling it is very good.

**Comment by SebastianStehle** [comment]
There are several topics.

1. What is a content?

The first question is: What is content for you? From what you are writing I guess for you it is content for websites, like articles and so on. But this is not true for everybody. One of our earliest customers is using Squidex for an warehouse and production system. They manage their production processes with Squidex. For myself as a developer the use case with inline editing is not a special case. There is much more content like feature toggles, supported currencies, languages, users and so on that must be managed somewhere. And from my perspective it is super annoying that these kind of content is very often managed in a very bad way. Others use Squidex as a product management system with little bit different requirements. Headless CMS also overlaps a little bit with Backend as a Service and I hope to combine those systems. Sometimes it is easy as providing multiple options and settings to define your custom workflow or just add an button like "Save and Publish".

2. Versioning?

Right now, everything uses event sourcing (https://martinfowler.com/eaaDev/EventSourcing.html). Therefore all changes, also in settings, assets, apps and so on have a history.  You get the history on the right side for free, basically. I am not sure, if it was a wise decision, because it makes some stuff more complicated, but you get a lot of other features for free as well. The archive collection is a different story.

3. Content variations?

When I talk about content variations, I mean for example the same t-shirt in red, blue and white. Localization is already supported.

**Comment by johnhorsema** [comment]
As the CMS grows, will the EventSourcing data exceed the capacity of the database? Is there a way to estimate this?

@SebastianStehle, any solution for us to save a 'snapshot' of the current state and backup to another location for storage (while the old states are purged)?
(See **Snapshots** in https://mikhail.io/2016/11/event-sourcing-and-io-complexity/)
