### ISSUE TITLE
Add Archive / Revert Delete Function

### ISSUE THREAD

**Issue by BoasE** [Squidex/squidex#36]
currently it is very easily possible to accidentally delete a schema. when this happens all contents of this schema isn't accessible anymore.

Squidex will still have this information in its history. So it would be nice to have some kind of Archive where i can see all deleted entries and having the ability to revert the deletion .

In this case we can handle disaster scenarios that are related to accidental deletions

**Comment by SebastianStehle** [comment]
One of the reasons why we use CQRS, will come sooner or later, but we need a good concept first.

**Comment by genschorck** [comment]
I agree that it is "too easy" to delete things and would like to see an alert to make the user confirm the action prior to deletion. Having a way to restore this would be ideal also.

**Comment by SebastianStehle** [comment]
Would you add an alert for all delete buttons?

**Comment by genschorck** [comment]
I think so. In our current system we have set a standard that anytime a user has the potential to lose data they see an alert to confirm (When a user chooses to Delete they are asked "Are you sure you want to delete this item?" or if they are working on something and choose to Cancel "You will lose any unsaved data. Are you sure you want to proceed?") It's an extra step, but I've not heard of any complaints due to this. Accidents are still bound to happen, but this is a fairly simple solution to help prevent it in most cases.
