### ISSUE TITLE
[Docs] Manual installation steps not accurate

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#63]
In the docs the manual installation section isn't accurate enough. When I type in `npm run install` it fails most of the time on Windows 10. I've tried it on 3 different machines. It usually rolls down to the fact that the compilers for Visual C++ are not installed to compile the node-sass package. The docs should state that on windows Visual C++ compilers are required before running the `npm run install` command.

The error message what I had for the first time:
```
14 verbose stack Error: squidex@1.0.0 build: `webpack --config app-config/webpack.run.prod.js --display-error-details --bail`
14 verbose stack Exit status 1
```

Once the `npm run build` command fails I had to install the VC compilers and run   
 `npm rebuild node-sass --force` and after that the `npm run build` command succeeds.

**Comment by SebastianStehle** [comment]
Hi,

thanks a lot. I never experienced the problem and was not aware of it. I guess because I have Visual Studio installed on all my devices and I use docker to build it (either the Dockerfile command to create a ready to user Docker Image or build.ps1 to generate the binaries for IIS).

Will try to improve the docs, pull requests are also very welcome :)

Thanks you very much :)

**Comment by SebastianStehle** [comment]
I added it to the docs.
